REM =======================================================
REM HR Module - Populate Data
REM Inserts foundational departments, employees, and child records
REM =======================================================

PROMPT Populating DEPARTMENTS...
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (10, 'EXE-01', 'Executive Management');
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (20, 'PM-01', 'Property Management');
INSERT INTO departments (dept_id, dept_code, dept_name) VALUES (30, 'FIN-01', 'Finance & Accounting');

PROMPT Populating EMPLOYEE_MASTER...
-- Note: emp_id is auto-generated by the identity column (Starts at 1)
INSERT INTO employee_master (first_name, last_name, work_email, current_dept_id, hire_date) 
VALUES ('Sarah', 'Connor', 's.connor@erp-project.com', 10, TO_DATE('01-JAN-2024', 'DD-MON-YYYY'));

INSERT INTO employee_master (first_name, last_name, work_email, current_dept_id, hire_date) 
VALUES ('John', 'Smith', 'j.smith@erp-project.com', 20, TO_DATE('15-MAR-2024', 'DD-MON-YYYY'));


PROMPT Populating EMP_PERSONAL_INFO (1-to-1)...
-- Linking to Sarah (emp_id = 1) and John (emp_id = 2)
INSERT INTO emp_personal_info (emp_id, home_address, personal_phone, emergency_contact_name, emergency_phone, blood_group)
VALUES (1, '123 Executive Tower, Marina, Dubai', '+971-50-1234567', 'Kyle Connor', '+971-50-9876543', 'O+');

INSERT INTO emp_personal_info (emp_id, home_address, personal_phone, emergency_contact_name, emergency_phone, blood_group)
VALUES (2, '456 Property Heights, Downtown, Dubai', '+971-55-1122334', 'Jane Smith', '+971-55-9988776', 'A-');


PROMPT Populating EMP_SALARY_SETTINGS (1-to-1)...
INSERT INTO emp_salary_settings (emp_id, base_salary, bank_name, account_number)
VALUES (1, 45000.00, 'AE123456789012345678901');

INSERT INTO emp_salary_settings (emp_id, base_salary, bank_name, account_number)
VALUES (2, 25000.00, 'AE987654321098765432109');


PROMPT Populating EMP_DOCUMENTS (1-to-Many)...
-- Sarah has two documents on file (Passport and Emirates ID)
INSERT INTO emp_documents (emp_id, doc_type, doc_no, issue_date, expiry_date, status, remarks)
VALUES (1, 'Passport', 'US987654321', TO_DATE('10-JAN-2020', 'DD-MON-YYYY'), TO_DATE('09-JAN-2030', 'DD-MON-YYYY'), 'active', 'Primary ID');

INSERT INTO emp_documents (emp_id, doc_type, doc_no, issue_date, expiry_date, status, remarks)
VALUES (1, 'Emirates ID', '784-1980-1234567-1', TO_DATE('01-FEB-2024', 'DD-MON-YYYY'), TO_DATE('31-JAN-2026', 'DD-MON-YYYY'), 'active', 'Residency ID');

-- John has one document on file
INSERT INTO emp_documents (emp_id, doc_type, doc_no, issue_date, expiry_date, status, remarks)
VALUES (2, 'Emirates ID', '784-1990-7654321-2', TO_DATE('15-MAR-2024', 'DD-MON-YYYY'), TO_DATE('14-MAR-2026', 'DD-MON-YYYY'), 'active', 'Residency ID');

COMMIT;
PROMPT HR Data Population Complete.
